# _config.yml for GitHub Pages

# Site settings
title: "BaaStream"
description: "Run automated checks on logs, infra, and configs for potential technical risks 🏥✨"
url: "https://baastream.com"   # Your domain (without / at the end)
baseurl: ""                  # Leave empty if deploying to root domain

# Author info (optional)
author:
  name: "Baa Stream"
  email: "support@baastream.com"

# Theme (GitHub Pages supports these: minima, cayman, slate, time-machine, etc.)
theme: minima

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclusions (files not processed by Jekyll)
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

# Permalinks
permalink: pretty

# Enable Google Analytics (optional)
# google_analytics: UA-XXXXXXXX-X
